### ISSUE TITLE
Change on setting page working only with the test elements

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.template#10]
I'm writing the second adapter for ioBroker. During the process on the first one there was an problem with Save button's activation when changing the settings.
Now on the second one there is the same problem again. 

Can anyone confirm this behavior with the original code?

The solutionfor me was to change the 'function load'.

Here is the code:
`    function load(settings, onChange) {
        // example: select elements with id=key and class=value and insert value
       if (!settings) return;
        $('.value').each(function () {
            var key = $(this).attr('id');
            var $key = $('#' + key + '.value');
            if ($key.attr('type') === 'checkbox') {
                $key.prop('checked', settings[key]).change(function() {
                    onChange();
                });
            } else {
                $key.val(settings[key]).change(function() {
                    onChange();
                }).keyup(function() {
                    onChange();
                });
            }
        });`

**Comment by Apollon77** [comment]
What about simply sending a "Pull rrequest "for your proposed change? It's easier to check the difference there :-)

**Comment by Jey-Cee** [comment]
Ok done ;-)

**Comment by Apollon77** [comment]
see #10

**Comment by AlCalzone** [comment]
Huh, I think I noticed that too recently. Gonna check out the changes later.
