### ISSUE TITLE
grunt is still referenced in the readme and documentation

### ISSUE THREAD

**Issue by DeepCoreSystem** [ioBroker/ioBroker.template#13]
As far as I know and understand, grunt was/is replaced by gulp.
But grunt is still used in the example commands in the readme.

I can't find a corresponding command in the gulpfile. 
How are we supposed to proceed with step 3 to rename the template?

**Comment by GermanBluefox** [comment]
Fixed. https://github.com/ioBroker/ioBroker.template/commit/254e400e85df6a902078043220777085fe4f8aa5
