### ISSUE TITLE
Setup (admin/index.html and admin/index_m.html) are different

### ISSUE THREAD

**Issue by BigDi** [ioBroker/ioBroker.template#20]
It take me some time to find out that the both index.html/index_m.html are different.
One time I used it in admin-2 and the other time in new admin and the setup page shows different entries.
From my point of view it should be consolidated.
There is also a bool value in index.html which should be declared as checkbox.

**Comment by Apollon77** [comment]
Yes they are and because admin2 is deprecated no new adapter should need to implement this, so I simply removed index.html from the repo here ... feel free to also do for your adapter :-)

**Comment by Apollon77** [comment]
PS: Admin3 uses Material to render config pages, Admin2 was based on jquery, so incompatible and because of this two files.
index.html was Admin2 and index_m.html is Admin3 compatible

**Comment by BigDi** [comment]
Unterstand.
OT: I used the Admin2 with Firefox@Android. Because the Admin3 is not working really good. When I scale the main screen I can't do anything and the Admin2 is working...

**Comment by Apollon77** [comment]
Admin2 is "EOL", will get no updates and new adapters most likely will have no configuration pages for admin2 anymore, so bad idea to stay on Admin2! 

Please report your Admin3 issues in the ioBroker.admin repo!
