### ISSUE TITLE
Upload utils.js to npm

### ISSUE THREAD

**Issue by qm3ster** [ioBroker/ioBroker.template#22]
The current way of having this completely vendor-supplied file in the `lib` directory of each project is a strange custom that discourages people from using the `lib` directory in conventional fashion (as far as I see from people's adapters).
And having it required as a normal third-party module would allow an easier update to it in the future.

**Comment by Apollon77** [comment]
Can you read minds? Work in progress ... will come soon in template and all others.
https://github.com/ioBroker/ioBroker.adapter-core

We are only waiting for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30546 to be accepted to publish it

**Comment by qm3ster** [comment]
Interesting approach to typedefs.

**Comment by jogibear9988** [comment]
fixed in #23

**Comment by jogibear9988** [comment]
@AlCalzone can you close?

**Comment by jogibear9988** [comment]
@Apollon77 can you close?

**Comment by qm3ster** [comment]
I can close :weary: :ok_hand:
