### ISSUE TITLE
Travis Node 6

### ISSUE THREAD

**Issue by schmupu** [ioBroker/ioBroker.template#39]
Hi, 
I am not sure if it is a problem? I saw in the .travis.yml you are testing node 6 too. In the main.js you are using async and await. I thought minimum requirement would be node 7 for async/await?
Stübi

**Comment by Apollon77** [comment]
Valid depending on es Version the Travis file should include node 6 or not

**Comment by schmupu** [comment]
Okay, I did not know it.

**Comment by Apollon77** [comment]
why close?

**Comment by Apollon77** [comment]
aah yes close here ... open new in adapter creator please
