### ISSUE TITLE
Log Issue

### ISSUE THREAD

**Issue by simpixo** [ioBroker/ioBroker.template#51]
Hallo

seit dem update auf JS Controller 2.x habe ich das Problem das obwohl der LOG Level auf "Warn" gestellt ist, im Log alles als "Info" angezeigt wird. Das müllt die ganze Logdatei zu. 

Lässt sich das beheben?

**Comment by AlCalzone** [comment]
Das issue gehört zu iobroker.js-controller
Das hier ist das repo für das adapter template.
