### ISSUE TITLE
TypeScriptVIS Error 'Cannot find start file!'

### ISSUE THREAD

**Issue by JonasHess** [ioBroker/ioBroker.template#53]
I get the error message "cannot find start file!" when starting the TypeScriptVIS project.
The adapter then shuts down.
I installed the adapter over Github (successfully)

Log:

 | error | startInstance template.0: cannot find start file!
 | info | object change system.adapter.template.0

**Comment by Apollon77** [comment]
The template is not really installable. It is just for developer reference. 

What you want tondo with it?

**Comment by AlCalzone** [comment]
That is because the TypeScript templates must be compiled before ioBroker can run them. Simply execute `npm run build`.

**Comment by JonasHess** [comment]
Thanks, running `npm run build` before pushing to GitHub solved the problem.
